// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/tunangoo/full-time-go-dev/hotel-reservation/internal/config"
	"github.com/tunangoo/full-time-go-dev/hotel-reservation/internal/handler"
	"github.com/tunangoo/full-time-go-dev/hotel-reservation/internal/middleware"
	"github.com/tunangoo/full-time-go-dev/hotel-reservation/internal/repository"
	"github.com/tunangoo/full-time-go-dev/hotel-reservation/internal/service"
	"github.com/uptrace/bun"

	_ "github.com/tunangoo/full-time-go-dev/hotel-reservation/docs"
)

// Injectors from wire.go:

func wireApp(db *bun.DB, jwtProvider config.TokenProvider) (*handler.Handler, error) {
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	hotelRepository := repository.NewHotelRepository(db)
	hotelService := service.NewHotelService(hotelRepository)
	hotelHandler := handler.NewHotelHandler(hotelService)
	roomRepository := repository.NewRoomRepository(db)
	bookingRepository := repository.NewBookingRepository(db)
	roomService := service.NewRoomService(roomRepository, hotelRepository, bookingRepository)
	roomHandler := handler.NewRoomHandler(roomService)
	authService := service.NewAuthService(userRepository, jwtProvider)
	authHandler := handler.NewAuthHandler(userService, authService)
	bookingService := service.NewBookingService(bookingRepository)
	bookingHandler := handler.NewBookingHandler(bookingService)
	jwtMiddleware := middleware.NewJWTMiddleware(jwtProvider, userRepository)
	handlerHandler := handler.NewHandler(userHandler, hotelHandler, roomHandler, authHandler, bookingHandler, jwtMiddleware)
	return handlerHandler, nil
}
