// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/tunangoo/full-time-go-dev/internal/handler"
	"github.com/tunangoo/full-time-go-dev/internal/repository"
	"github.com/tunangoo/full-time-go-dev/internal/service"
	"github.com/uptrace/bun"
)

// Injectors from wire.go:

func wireApp(db *bun.DB) (*handler.Handler, error) {
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	handlerHandler := handler.NewHandler(userHandler)
	return handlerHandler, nil
}
