basePath: /api
definitions:
  gin.H:
    additionalProperties: {}
    type: object
  github_com_tunangoo_full-time-go-dev_internal_model.CreateUserRequest:
    properties:
      email:
        type: string
      first_name:
        maxLength: 255
        minLength: 3
        type: string
      last_name:
        maxLength: 255
        minLength: 3
        type: string
      password:
        maxLength: 255
        minLength: 8
        type: string
    required:
    - email
    - first_name
    - last_name
    - password
    type: object
  github_com_tunangoo_full-time-go-dev_internal_model.ErrorResponse:
    properties:
      code:
        type: integer
      detail:
        type: string
      message:
        type: string
    type: object
  github_com_tunangoo_full-time-go-dev_internal_model.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
      password:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:7000
info:
  contact:
    email: support@full-time-go-dev.com
    name: API Support
  description: Full Time Go Dev API
  title: Full Time Go Dev API
  version: "1.0"
paths:
  /v1/user/{id}:
    get:
      consumes:
      - application/json
      description: Get user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/gin.H'
            - properties:
                user:
                  $ref: '#/definitions/github_com_tunangoo_full-time-go-dev_internal_model.User'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_tunangoo_full-time-go-dev_internal_model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_tunangoo_full-time-go-dev_internal_model.ErrorResponse'
      summary: Get user
      tags:
      - user
  /v1/user/all:
    get:
      consumes:
      - application/json
      description: List all user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/gin.H'
            - properties:
                total:
                  type: integer
                users:
                  items:
                    $ref: '#/definitions/github_com_tunangoo_full-time-go-dev_internal_model.User'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_tunangoo_full-time-go-dev_internal_model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_tunangoo_full-time-go-dev_internal_model.ErrorResponse'
      summary: List all user
      tags:
      - user
  /v1/user/create:
    post:
      consumes:
      - application/json
      description: Create user
      parameters:
      - description: Create user request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_tunangoo_full-time-go-dev_internal_model.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/gin.H'
            - properties:
                message:
                  type: string
                user:
                  $ref: '#/definitions/github_com_tunangoo_full-time-go-dev_internal_model.User'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_tunangoo_full-time-go-dev_internal_model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_tunangoo_full-time-go-dev_internal_model.ErrorResponse'
      summary: Create user
      tags:
      - user
schemes:
- http
swagger: "2.0"
